options(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/latest'))
install.packages('remotes')
remotes::install_version("shiny", version = "1.7.0")
remotes::install_version("shinydashboard", version = "0.7.1")
remotes::install_version("shinyWidgets", version = "0.6.2")
remotes::install_version("shinyjs", version = "2.0.0")
remotes::install_version("shinycssloaders", version = "1.0.0")
remotes::install_version("purrr", version = "0.3.4")
remotes::install_version("lubridate", version = "1.7.10")
remotes::install_version("tibble", version = "3.1.4")
remotes::install_version("dplyr", version = "1.0.7")
remotes::install_version("tidyr", version = "1.1.4")
remotes::install_version("DT", version = "0.19")
remotes::install_version("config", version = "0.3.1")
remotes::install_version("qs", version = "0.25.1")
remotes::install_version("polished", version = "0.4.0")
remotes::install_version("fs", version = "1.5.0")
remotes::install_version("rlang", version = "0.4.11")
remotes::install_version("htmltools", version = "0.5.2")
remotes::install_github("merlinoa/summaryrow", ref = "027d02143ef465467f99e887b7c4f024a2445d7f")
remotes::install_github("ractuary/devtri", ref = "5b2ff605b61bbd444d6eeca19ed7d0a4298abccf")
